#!/usr/bin/env bash
# script that displays a list of currently running processes.
# Requirements:

#    Must show all processes, for all users, including those which might not have #  TTY
#   Display in a user-oriented format
#  Show process hierarchy

ps auxf
