#!/usr/bin/env bash
# Bash script that displays the PID, along with the process name,
# if processes whose name contain the word bash.

main=$(pgrep -f bash)

for _ in $main
do
	name=$(ps -o comm= -p "$main")
	echo "$main $name"
done
