#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely.
# Requirement
#	in betweeen each iteration of the loop, add a sleep 2


while true; do
  echo "To infinity and beyond"
done
