#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.
# script should only display:
#    username
#    user id
#    Home directory path for the user
################################3333333333333333333########################


while IFS=":" read -r username _ userid  _ _ homedir _
do
	echo "$username:$userid:$homedir"
done < /etc/passwd

