#!/usr/bin/env bash
#script that displays the time of 12 hours and 59 minutes

minute="1"
i="0"
echo "Hour: $i"
while ((i<12))
do
  echo "$minute"
  if ((minute==59))
  then
    minute="0"
    ((i++))
    echo "Hour: $i"
  fi
  ((minute++))
done