#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

i="1"
count="0"

while [ $count -ne 13 ]; do
	echo "Hour: $count"
while [[ "$i" -ne "60" ]]
do
	echo "$i"
	(( i++ ))
done
(( count++ ))
i="1"
done
