#!/usr/bin/env bash
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for i in *
do 
	if [[ -f "$i" ]] && ! [[ "$i" == .* ]]
	then
		param="${i#*-}"
		echo "$param"
	fi
done
