#!/usr/bin/env bash
#performs some checks on files
file="school"
if [ -e "$file" ]
then
  echo "$file file exists"
  if [ -s "$file" ]; then
    echo "school file is not empty"
  elif [ ! -s "#file" ]; then
    echo "school file is empty"
  elif [ -f "$file" ]; then
    echo "school is a regular file"
  fi
else
  echo "$file file does not exist"
fi