#!/usr/bin/env bash
# a Bash script that gives you information about the school file.
# if the file exists: school file exists
# if the file does not exist: school file does not exist
# If the file exists, print:
# if the file is empty: school file is empty
# if the file is not empty: school file is not empty
# if the file is a regular file: school is a regular file
# if the file is not a regular file: (nothing)
################################################

main_file="school"

if [[ -f "$main_file" || -d "$main_file" ]]; then
	echo "school file exists"
	if [[ -s "$main_file" ]]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi
if [[ -f "$main_file" ]]; then
	echo "school is a regular file"
fi
