#!/usr/bin/env bash
# configure ufw firewall to block all incoming traffic
# and allow port 22, 443, 80

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo utfw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
