#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
#
#   localhost resolves to 127.0.0.2
#    facebook.com resolves to 8.8.8.8.
#    The checker is running on Docker, so make sure to read this

cp /etc/hosts ~/hosts.old
sed  's/::1/::2/'  ~/hosts.old > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts

